def columns_select(df):
    # 残したいカラム一覧を定義
    selected_columns = [
        "Code",
        "CompanyName",
        "Sector17CodeName",
        "Sector33CodeName",
        "MarketCodeName"
    ]
    # 存在するカラムだけを選択（安全対策）
    selected_columns = [col for col in selected_columns if col in df.columns]
    return df[selected_columns].copy()

# financial
"""
"DisclosureNumber",
"LocalCode",
"TypeOfDocument",
"TypeOfCurrentPeriod",
"DisclosedDate",
"CurrentPeriodEndDate",
"AverageNumberOfShares",
"NetSales",
"OperatingProfit",
"OrdinaryProfit",
"Profit",
"Cost_of_sales",
"GrossProfit",
"Selling_general_and_administrative_expenses",
"NetSales_Forecast",
"OperatingProfit_Forecast",
"OrdinaryProfit_Forecast",
"Profit_Forecast",
"EPS_Forecast",
"NetSales_quarter",
"OperatingProfit_quarter",
"OrdinaryProfit_quarter",
"Profit_quarter",
"GrossProfit_quarter",
"Selling_general_and_administrative_expenses_quarter",
"NetSales_TTM",
"OperatingProfit_TTM",
"OrdinaryProfit_TTM",
"Profit_TTM",
"GrossProfit_TTM",
"Selling_general_and_administrative_expenses_TTM",
"margin_OperatingProfit",
"margin_OperatingProfit_quarter",
"margin_OperatingProfit_TTM",
"margin_GrossProfit",
"margin_GrossProfit_quarter",
"margin_GrossProfit_TTM",
"margin_Profit",
"margin_Profit_quarter",
"margin_Profit_TTM",
"margin_OrdinaryProfit",
"margin_OrdinaryProfit_quarter",
"margin_OrdinaryProfit_TTM",
"growth_YoY_GrossProfit",
"growth_YoY_GrossProfit_TTM",
"growth_YoY_GrossProfit_quarter",
"growth_YoY_Selling_general_and_administrative_expenses",
"growth_YoY_Selling_general_and_administrative_expenses_TTM",
"growth_YoY_Selling_general_and_administrative_expenses_quarter",
"growth_YoY_NetSales",
"growth_YoY_NetSales_TTM",
"growth_YoY_NetSales_quarter",
"growth_forward_NetSales",
"growth_forward_OperatingProfit",
"growth_forward_OrdinaryProfit",
"growth_forward_Profit",
"NetSales_Forecast_RevisionEarn",
"OperatingProfit_Forecast_RevisionEarn",
"OrdinaryProfit_Forecast_RevisionEarn",
"Profit_Forecast_RevisionEarn",
"DisclosedDate_RevisionEarn",
"growth_forward_RevisionEarn_NetSales",
"growth_forward_RevisionEarn_OperatingProfit",
"growth_forward_RevisionEarn_OrdinaryProfit",
"growth_forward_RevisionEarn_Profit",
"growth_forward_model_NetSales"
"""